version: "3"

services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:80
    environment:
      - NODE_ENV=prod
      - NODE_PATH=/usr/app/node_modules
      - SERVER_URL=server:8000
    links:
      - server

  server:
    build:
      context: ./server/
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - /usr/app
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=prod
      - NODE_PATH=/usr/app/node_modules
      - MONGODB_URI=<ATLAS SRV>
      - MONGODB_NS=todos
    command: nodemon index.js
